# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

JAVA_MAVEN_BOOTSTRAP="Y"
inherit java-maven-2

DM_GENERATED_SOURCES="doxia-decoration-model-gen-src-${PV}.tar.bz2"
DESCRIPTION="Maven is a software project management and comprehension tool."
HOMEPAGE="http://maven.apache.org/"
SRC_URI="http://dev.gentooexperimental.org/~kiorky/${P}.tar.bz2
http://dev.gentooexperimental.org/~kiorky/${DM_GENERATED_SOURCES}"
LICENSE="as-is" # http://plexus.codehaus.org/plexus-utils/license.html
SLOT="0"
KEYWORDS="~x86"
IUSE="source doc"
DEP="=dev-java/plexus-container-default-1.0_alpha9
dev-java/plexus-utils
=dev-java/jakarta-oro-2.0*
dev-java/junit
dev-java/plexus-i18n
dev-java/velocity
dev-java/plexus-velocity"
DEPEND=">=virtual/jdk-1.4 ${DEP}"
RDEPEND=">=virtual/jre-1.4 ${DEP}"

EANT_GENTOO_CLASSPATH="
plexus-container-default-1.0_alpha9
plexus-utils
jakarta-oro-2.0
junit
plexus-i18n
plexus-velocity
velocity
"
# add  a patch to add interdeps while compiling:
#  doxia-sink-api for core
#  doxia-core     for tkwiki
#  doxia-decoration-model for siterdr
#  doxia-core for siterdr
EMAVEN_PROJECTS="doxia-sink-api doxia-core doxia-decoration-model doxia-site-renderer doxia-modules/doxia-module-confluence doxia-modules/doxia-module-docbook-simple doxia-modules/doxia-module-twiki"

src_unpack(){
	java-maven-2_src_unpack
	# add java sources generated by a maven plugin
	cd "${S}/doxia-decoration-model/src/main/java/" || die
	unpack "${DM_GENERATED_SOURCES}"
}
