#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

PIDFILE="/var/run/${SVCNAME}.pid"

depend() {
	use net
}

checkconfig() {
	# GORILLA_HOST and GORILLA_PORT must be set
	if [ -z ${GORILLA_HOST} ] ; then
		eerror "GORILLA_HOST must be set in order for ${SVCNAME} to run."
		return 1
	fi
	if [ -z ${GORILLA_PORT} ] ; then
		eerror "GORILLA_PORT must be set in order for ${SVCNAME} to run."
		return 1
	fi

	# Use sensible defaults
	GORILLA_USER=${GORILLA_USER:-nobody}
	GORILLA_GROUP=${GORILLA_GROUP:-nobody}
	GORILLA_JVMARGS=${GORILLA_DIR:--server}

	if [ "${GORILLA_USER}" == "root" ] ; then
		ewarn "${SVCNAME} is being run as root; this is not a good idea."
	fi
	return 0
}

start() {
	ebegin "Starting ${SVCNAME}"
	
	[ checkconfig ] || eend 1

	java=$(java-config-2 -J)
	cp="$(java-config-2 -d -p gorilla)"
	start-stop-daemon --start --quiet \
		--background --make-pidfile --pidfile "${PIDFILE}" \
		--user ${GORILLA_USER}:${GORILLA_GROUP} \
		--stdout /dev/null --stderr /dev/null \
		--exec ${java} -- \
			${GORILLA_JVMARGS} -cp ${cp} \
			com.martiansoftware.nailgun.NGServer ${GORILLA_HOST}:${GORILLA_PORT}
	eend $?
}
