#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

prog_name="gnatsd"
pid_file="/var/run/${prog_name}.pid"
log_file="/var/log/${prog_name}.log"


depend() {
	need net
}

start() {
	ebegin "Starting NATS"
		start-stop-daemon --start -p ${pid_file} -b -m -1 ${log_file} -2 ${log_file} -x /usr/bin/${prog_name}
	eend $?
}

stop() {
	ebegin "Stopping NATS"
		start-stop-daemon --stop -p ${pid_file}
	eend $?
}

