--- a/Makefile.orig	2017-09-22 21:58:58.385697674 +0300
+++ b/Makefile	2017-09-22 21:59:19.719031421 +0300
@@ -1,11 +1,20 @@
 # For building for the current running version of Linux
 TARGET		:= $(shell uname -r)
-HOME=$(shell pwd)
-# Or for a specific version
+# Or specific version
 #TARGET		:= 2.6.33.5
 KERNEL_MODULES	:= /lib/modules/$(TARGET)
-# KERNEL_BUILD	:= $(KERNEL_MODULES)/build
+
+ifneq ("","$(wildcard /usr/src/linux-headers-$(TARGET)/*)")
+# Ubuntu
 KERNEL_BUILD	:= /usr/src/linux-headers-$(TARGET)
+else
+ifneq ("","$(wildcard /usr/src/kernels/$(TARGET)/*)")
+# Fedora
+KERNEL_BUILD	:= /usr/src/kernels/$(TARGET)
+else
+KERNEL_BUILD	:= $(KERNEL_MODULES)/build
+endif
+endif
 
 #SYSTEM_MAP	:= $(KERNEL_BUILD)/System.map
 SYSTEM_MAP	:= /boot/System.map-$(TARGET)
@@ -15,11 +24,20 @@
 # Directory below /lib/modules/$(TARGET)/kernel into which to install
 # the module:
 MOD_SUBDIR = drivers/hwmon
+MODDESTDIR=$(KERNEL_MODULES)/kernel/$(MOD_SUBDIR)
 
-obj-m	:= $(DRIVER).o
+obj-m	:= $(patsubst %,%.o,$(DRIVER))
+obj-ko  := $(patsubst %,%.ko,$(DRIVER))
 
 MAKEFLAGS += --no-print-directory
 
+ifneq ("","$(wildcard $(MODDESTDIR)/*.ko.gz)")
+COMPRESS_GZIP := y
+endif
+ifneq ("","$(wildcard $(MODDESTDIR)/*.ko.xz)")
+COMPRESS_XZ := y
+endif
+
 .PHONY: all install modules modules_install clean
 
 all: modules
@@ -27,10 +45,17 @@
 # Targets for running make directly in the external module directory:
 
 modules clean:
-	@$(MAKE) -C $(KERNEL_BUILD) M=$(CURDIR) $@ EXTRA_CFLAGS=-g
+	@$(MAKE) -C $(KERNEL_BUILD) M=$(CURDIR) $@
 
 install: modules_install
 
 modules_install:
-	cp $(DRIVER).ko $(KERNEL_MODULES)/kernel/$(MOD_SUBDIR)
+	mkdir -p $(MODDESTDIR)
+	cp $(DRIVER).ko $(MODDESTDIR)/
+ifeq ($(COMPRESS_GZIP), y)
+	@gzip -f $(MODDESTDIR)/$(DRIVER).ko
+endif
+ifeq ($(COMPRESS_XZ), y)
+	@xz -f $(MODDESTDIR)/$(DRIVER).ko
+endif
 	depmod -a -F $(SYSTEM_MAP) $(TARGET)
